[["Carol Borba","channel\/UCw_S3AgRp0t-iXw4x5aaZ_Q","https://yt3.ggpht.com\/ytc\/AAUvwngQrG7feLin_yMQb06DhEvTmBlbdUD9fyvXnC43sQ=s256-c-k-c0x00ffffff-no-rj"],["Roberta's Gym Brasil","channel\/UC5KN7SPqLxNUvaKGwHRMYiw","https://yt3.ggpht.com\/ytc\/AAUvwngy0wlCGW677DmPJHiaOGxNAcknMOb37zJEW_8Y=s256-c-k-c0x00ffffff-no-rj"],["Sérgio Bertoluci","channel\/UCxSYXfUx1bIQHoRH6hIDQnw","https://yt3.ggpht.com\/ytc\/AAUvwniCpBLU5lF-uPF1bFcAxZh0ENLEawLrGEriQSqHIvI=s256-c-k-c0x00ffffff-no-rj"],["Coach Rubens Gomes","channel\/UCaZLOsun_sY6BonjwR8Zo4A","https://yt3.ggpht.com\/ytc\/AAUvwnj_erCBM8STMlP6dZl1TwZaO2qAmX9D3hyhu1dQug=s256-c-k-c0x00ffffff-no-rj"],["Musculos e Corpo Definido","channel\/UC6QSBmXiK7vwW3DcQpop31g","https://yt3.ggpht.com\/ytc\/AAUvwngiBnXDZONEGLQqUwkOfF-yv-klPGjV7qpZJlh3CA=s256-c-k-c0x00ffffff-no-rj"],["Cia Athletica","channel\/UCwbAMFd0PjfDLqghvSrX2qw","https://yt3.ggpht.com\/ytc\/AAUvwni6zQ0zCYqBK1UnWHkr0KyYEVAgfAqV_0swaTq89A=s256-c-k-c0x00ffffff-no-rj"],["Pri Leite Yoga","channel\/UCehH0gfC-ivKz_htoMHxHtA","https://yt3.ggpht.com\/ytc\/AAUvwngnjoNFO-L9dJHdZ2kF8ndfHOJwOWFbihuZueCJ9g=s256-c-k-c0x00ffffff-no-rj"],["Fernanda Yoga","channel\/UCod2Gi9j8THW1hC7sHn94Rw","https://yt3.ggpht.com\/ytc\/AAUvwnj4COIC44FfYqKMF1uD4TtCwogzGbuPIqgF0THsFw=s256-c-k-c0x00ffffff-no-rj-mo"],["Fit Dance","channel\/UCl_AQeO6ynSDRSjclc1e16Q","https://yt3.ggpht.com\/ytc\/AAUvwngc9UVhTzyZ8pM8WbknfMJyyo7h6RluaIXbaItW_Q=s256-c-k-c0x00ffffff-no-rj"],["Irtylo Santos","channel\/UCG0ATfKGqkiq46rQ_B3yIkw","https://yt3.ggpht.com\/ytc\/AAUvwngaqzFmJEgLZq44Nom1pakC5RJRlpIszDqo88-Dnw=s256-c-k-c0x00ffffff-no-rj"]]


































